version: "3.9"
services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes: 
      - /etc/nginx/certs/:/etc/nginx/certs/
      - ./nginx.conf:/etc/nginx/nginx.conf
